events {}
http {
    server {
        listen 80;
        location / {
            proxy_pass http://router-luci:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_buffering off;
            proxy_http_version 1.0;
            proxy_set_header Connection "";
        }
    }
}
